server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: ly-saas
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oidc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: hfb568326
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

jwt:
  secret: mtVMObZlD4Fz6V3wpwuHvJWFrnSoTLel
  expiration: 86400 # 24小时

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ly.saas.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# RocketMQ主题配置
rocketmq:
#  name-server: 192.168.50.29:9876
  name-server: localhost:9876
  topic:
    test: test-topic  # 测试主题
  producer:
#    access-key: admin
#    secret-key: admin
    group: shu-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 0
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-next-server: true
    enable-msg-trace: true
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC
  consumer:
#    access-key: admin
#    secret-key: admin
    group: shu-consumer-group
    consume-thread-max: 64
    consume-thread-min: 20
    enable-msg-trace: true
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC

logging:
  level:
    com.ly.saas: info

# 租户到环境映射配置 (本地配置作为备份，优先从Consul获取)
tenant:
  mapping:
    dingding: wei
    qiwei: wu
    huawei: shu
  default-environment: shu
  config:
    enabled: true  # 是否启用Consul配置
    refresh-interval: 10  # 配置刷新间隔(秒)